pypi-qtpy: Autospec creation for update from version 2.3.1 to version 2.4.0
Anton Yablokov (1):
      Approve style correction suggested by @CAM-Gerlach

C.A.M. Gerlach (7):
      Just except ImportError, not redundant ModuleNotFound importing OpenGL
      Use more concise language & refer to PR in QOpenGL comments
      Rename MISSING_OPENGL_NAMES module attribute to _missing_optional_names
      Add __cause__ to optional import errors & refactor logic into helper
      CI: Use unique envs for each binding & tweak shell options
      CI: Replace Conda with Mamba for faster & more stable/accurate solves
      CI: Create env & install Qt deps in one pass for further speedups

Daelon Suzuka (4):
      Change _QTOPENGL_NAMES to a set
      Apply suggestions from code review
      Update qtpy/QtGui.py
      Move module __getattr__ to top for better visibility and remove underscore from _getattr_missing_optional_dep

Daniel Althviz Moré (4):
      Apply suggestions from code review
      Apply suggestions from code review
      Apply suggestions from code review
      Apply suggestions from code review

David Kincaid (12):
      Remove OpenGL imports to improve modularity
      Implement delayed import error mechanism designed by @CAM-Gerlach
      Refactor one file for comparison
      Add missing "as error"
      Fix QtGui.py to import the correct OpenGL module
      Move OpenGL import names to a module-level list
      Fix lines that had 7 spaces for some reason
      Fix typo in comments
      Sort list of opengl names
      Add opengl import tests for QtWidgets and QtGui
      Add a test for the deferred import error mechanism
      Add trailing newlines

Grzegorz Bokota (11):
      enable more test on CI
      try uncomment additional test
      add concurecy calculation
      fix import
      enable test_isalive
      Add compat layer for QFileDialog
      Apply suggestions from code review
      Update qtpy/tests/test_qtwidgets.py
      Update .github/workflows/ci.yml
      setup pre-commit
      add `.git-blame-ignore-revs`

Jan Robert Schmidt (2):
      replace custom implementation with loadUiType from PySide6
      skip test_load_ui_type if pyside6-uic not available

Philipp Temminghoff (1):
      add QEnum macro for PyQt bindings

StSav012 (7):
      Make `QtWidgets.QToolBar.addAction` compatible with Qt6 arguments' order
      Make `exec()` for PySide2
      Fix a test failure on PyQt5 5.9
      Make `Q*.addAction` compatible for Qt < 6.3
      Fix a test failure on PyQt5 5.9
      Add a description for `add_action`
      Use `QT_VERSION` instead of `QtCore.__version__`

Wiktor Kraśnicki (1):
      Add tests and change toml boolean values to lowercase

dalthviz (27):
      Back to work
      Add missing issue closed for v2.3.1 changelog entry
      CI: Update bindings upper bound version to 6.5
      Check 'Qt.ItemFlags' access
      Add 'Qt.ItemFlags' definition as 'Qt.ItemFlag' alias for PyQt6
      Add mappings for deprecated QDropEvent pos and posF methods
      Skip QEnum test for PySide2 < 5.15
      Test using PyQt extra packages
      Testing
      Modify 'QDatavisualization' ('QDataVisualization' with lower 'v') access test
      Check QtWidgets.QFileDialog.Options definition
      Add QtWidgets.QFileDialog.Options as alias of QtWidgets.QFileDialog.Option
      Unskip QtNetworkAuth test for PyQt bindings
      Improve enum to flags aliasing for PyQt6
      Testing
      Add missing staticmethod decorator to kwargs renaming wrapper function
      Refactor kwargs wrapper functions and define a general static methods kwargs wrapper function in _utils
      Set default value to check PyQt extra packages to 'No'. Change QScintilla testing for PyQt6
      Add way to check job matrix values
      Update macOS extra packages to be installed with Python 3.11. Improve job config/matrix values display
      Update check values step. Try to test PySide6 6.5 on Windows using conda
      Fix job/matrix values check step. Test with PyQt6 6.5 Python 3.11 pip
      Use PySide6 6.5 in conda with Python 3.11
      Update README with testing matrix values. Update typing section content
      Improvements and fixes to the README changes
      More improvements to the README
      Release 2.4.0

stsav012 (22):
      Symmetrize `path` and `location` of `QLibraryInfo`
      Fix AttributeError: type object 'LibraryLocation' has no attribute 'PrefixPath' on PyQt5
      Symmetrize `QDateTime.toPython` and `toPyDateTime`, etc.
      Remove forgotten code
      Test static `QMenu.exec_` call
      Call static `QMenu.exec` when necessary
      Try 1 to fix a stall on Windows
      Try 2 to fix a stall on Windows
      Try 3 to fix a stall on Windows
      Resolve the merging conflict
      Resolve the merging conflict
      Resolve the merging conflict
      Parametrize tests, as @CAM-Gerlach suggested
      Avoid double-assignment of a module-level constant, as @CAM-Gerlach suggested
      Add `datetime.*` type checks, as @CAM-Gerlach suggested
      Call static `Q*Application.exec` when necessary
      Fix the error when an `exec_` has no arguments at all
      Skip tests for `QGuiApplication.exec_` and `QApplication.exec_` with `conda=No`
      Remove underscore prefix from `possibly_static_exec`
      Clean up imports
      Revert "Clean up imports"
      Rename `utils.py` → `_utils.py`

wkrasnicki (2):
      Add CLI option to generate Pyright config
      Update README on how to configure Pyright