pypi-qtpy: Autospec creation for update from version 2.4.1 to version 2.4.2
Anton Yablokov (1):
      Test `QMenu.addAction` with various shortcut types

Carlos Cordoba (1):
      Replace Quansight logo by CZI one in Readme

Daniel Althviz Moré (2):
      Apply suggestions from code review
      CI: Update macOS image to use x86 image

Mark Harfouche (2):
      Help users understand why 6.8.0 just destroys things
      Update qtpy/__init__.py

Pierre Raybaut (1):
      Add QtCore.Qt.MouseButton.MidButton alias for Qt6

StSav012 (11):
      Make `QAction.setShortcut`(`s`) accept many types
      Move the `QAction.setShortcut` patch to `QtGui`
      Fix AttributeError: type object 'Key' has no attribute 'Key_F1' on old PyQt5
      Patch `QAction.setShortcut`(`s`) for Qt < 6.4
      Fix AttributeError: type object 'Key' has no attribute 'Key_F1' on old PyQt5
      Patch `addAction` for Qt < 6.4
      Apply code style suggestions by @ccordoba12
      Move imports to be at the beginning of the file as suggested by @ccordoba12
      Clarify the comment as suggested by @ccordoba12
      Import only `QAction` separately as suggested by @ccordoba12
      Test whether `QAction.setShortcuts` doesn't support a `Qt.Key` argument as suggested by @ccordoba12

dalthviz (9):
      CI: Remove basedir flag for coverage command
      Testing
      Testing
      Back to work
      CI: Upload coverage via Coveralls GitHub Action
      Add coverage xml report format to try to workaround coveralls action issue
      CI: Update 'pytest.importorskip' usage
      Add assert for new button alias 'Qt.MouseButton.MidButton'
      Release 2.4.2

pre-commit-ci[bot] (6):
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks